version: '3.8'

services:
  maintainerr-overlay-helperr:
    image: pierredurrr/maintainerr-overlay-helperr:latest
    environment:
      PLEX_URL: "http://plex-server-ip:32400"
      PLEX_TOKEN: "PLEX-TOKEN"
      MAINTAINERR_URL: "http://maintainerr-ip:6246/api/collections"
      IMAGE_SAVE_PATH: "/images"
      ORIGINAL_IMAGE_PATH: "/images/originals"
      TEMP_IMAGE_PATH: "/images/temp"

      # Change the values here to customize the overlay
      FONT_PATH: "/fonts/AvenirNextLTPro-Bold.ttf"
      FONT_COLOR: "#ffffff"
      BACK_COLOR: "#B20710"
      FONT_SIZE: "45"
      PADDING: "15"
      BACK_RADIUS: "20"
      HORIZONTAL_OFFSET: "80"
      HORIZONTAL_ALIGN: "center"
      VERTICAL_OFFSET: "40"
      VERTICAL_ALIGN: "bottom"
      
      RUN_INTERVAL: "2"  # Set the run interval to after X minutes; default is 480 minutes (8 hours) if not specified
    volumes:
      - /docker_data2/maintainerr-overlay-helper/config/images:/images
      - /docker_data2/maintainerr-overlay-helper/config/fonts:/fonts
    network_mode: "bridge"
