version: '3.8'

services:
  maintainerr-overlay-helperr:
    image: gsariev/maintainerr-overlay-helperr:latest
    environment:
      PLEX_URL: "http://plex-server-ip:32400"
      PLEX_TOKEN: "PLEX-TOKEN"
      MAINTAINERR_URL: "http://maintainerr-ip:6246/api/collections"
      IMAGE_SAVE_PATH: "/images"
      ORIGINAL_IMAGE_PATH: "/images/originals"
      TEMP_IMAGE_PATH: "/images/temp"
      FONT_PATH: "/fonts/AvenirNextLTPro-Bold.ttf"
    volumes:
      - ./images:/images
      - ./fonts:/fonts
    network_mode: "bridge"